param = {};
window.location.href.replace(location.hash, '').replace(
        /[?&]+([^=&]+)=?([^&]*)?/gi, // regexp
        function (m, key, value) { // callback
            param[key] = value !== undefined ? value : '';
        }
);
nb = parseInt(param.p);

var panier = [{
        type: "",
        prix: 0,
        taille: "",
        couleur: "",
        description: "",
        image: ""
    }
];
var tout = '';
produits = [
//    ROBES
    {
        "type": "Swing Robe Fiona Femme",
        "prixmin": "87.24",
        "prixmax": "145.67",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Blanche",
        "description": ["100% Polyester", "Lavage ? sec uniquement", "Manches 3/4"],
        "image1": "swing/swing_b1.jpg",
        "image2": "swing/swing_b2.jpg",
        "image3": "swing/swing_b3.jpg",
        "image4": "swing/swing_b4.jpg",
        "index": "0"
    },
    {
        "type": "Swing Robe Fiona Femme",
        "prixmin": "83.97",
        "prixmax": "119.95",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Rouge",
        "description": ["100% Polyester", "Lavage ? sec uniquement", "Manches 3/4"],
        "image1": "swing/swing_b1r.jpg",
        "image2": "swing/swing_b2r.jpg",
        "image3": "swing/swing_b3r.jpg",
        "image4": "swing/swing_b4r.jpg",
        "index": "1"
    },
    {
        "type": "swing/swing_c2",
        "prixmin": "24.99",
        "prixmax": "42.67",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Rouge",
        "description": ["100% viscose, 100% Polyester", "Lavage en machine 30 max", "Sans Manches"],
        "image1": "swing/swing_c1.jpg",
        "image2": "swing/swing_c2.jpg",
        "image3": "swing/swing_c3.jpg",
        "image4": "swing/swing_c4.jpg",
        "index": "2"
    },
    {
        "type": "HomRain Robe Vintage Femme Elegante Pin up High Low Jupe Asymétrique pour Soirée Cocktail Bal Mariage Réunoin Fête",
        "prixmin": "78.99",
        "prixmax": "92.95",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Verte",
        "description": ["Dentelle, tissu dentelle florale de haute qualité qui est élégant et lice.", "Laver à la main ou en machine dans un sac à ligne et suspendre à sécher.", "Fermeture: Fermeture éclair",
            "taille haute,jupe courte devant longue dernière.",
            "Type de col: Col grand bateau affiche le beau vue de l'épaule.",
            "Veuillez voir notre tableau de taille pour bien choisir la taille, non celui d'Amazon.",
            "Sans manche,robe asymétrique courte devant longue dernière,idéale pour mariage,soirée,cocktail,guinguette,bal,anniversaire,fête etc."],
        "image1": "swing/swing_sina1.jpg",
        "image2": "swing/swing_sina2.jpg",
        "image3": "swing/swing_sina3.jpg",
        "image4": "swing/swing_sina4.jpg",
        "index": "3"
    },
    {
        "type": "Homeyee Vintage à manche 3/4 en dentelle florale brodée cocktail",
        "prixmin": "37.99",
        "prixmax": "45.18",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Rouge",
        "description": ["95% Polyester", "5% Elasthanne", "Manches 3/4"],
        "image1": "swing/homeye_r1.jpg",
        "image2": "swing/homeye_r2.jpg",
        "image3": "swing/homeye_r3.jpg",
        "image4": "swing/homeye_r4.jpg",
        "index": "4"
    },
    {
        "type": "KoJooin Robe de Soirée Femme Dentelle Audrey Hepburn 1950 Robe Vintage Rétro Élégant Robe de Cocktail années 50",
        "prixmin": "26.99",
        "prixmax": "32.99",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Bleue",
        "description": ["97% Polyester", "3% Spandex", "Col rond, taille Élastique,"],
        "image1": "swing/kojooin_b1.jpg",
        "image2": "swing/kojooin_b2.jpg",
        "image3": "swing/kojooin_b3.jpg",
        "image4": "swing/kojooin_b4.jpg",
        "index": "5"
    },
//    PANTALONS
    {
        "type": "Pantalon Homme",
        "prixmin": "24.16",
        "prixmax": "28.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Gris",
        "description": ["63% Polyester", "35% Viscose", "2% Élasthanne", "lavage en machine (40°C)", "Fermeture: Fermeture éclair et crochet", "taille normale"],
        "image1": "pantalon_homme/pantalon1_gris.jpg",
        "image2": "pantalon_homme/pantalon2_gris.jpg",
        "image3": "pantalon_homme/pantalon3_gris.jpg",
        "image4": "pantalon_homme/pantalon4_gris.jpg",
        "index": "6"
    },
    {
        "type": "Pantalon Homme",
        "prixmin": "20.76",
        "prixmax": "32.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["98% Coton, 2% Élasthanne", "Lavage en machine, 30° max.", "Fermeture: Bouton"],
        "image1": "pantalon_homme/pantalon1_noir.jpg",
        "image2": "pantalon_homme/pantalon2_noir.jpg",
        "image3": "pantalon_homme/pantalon3_noir.jpg",
        "image4": "pantalon_homme/pantalon4_noir.jpg",
        "index": "7"
    },
    {
        "type": "Pantalon Homme",
        "prixmin": "5.97",
        "prixmax": "21.90",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Marron",
        "description": ["98% Coton, 2% Élasthanne", "lavage en machine (40°C)", "Fermeture: Fermeture éclair", "taille normale"],
        "image1": "pantalon_homme/pantalon1_marron.jpg",
        "image2": "pantalon_homme/pantalon2_marron.jpg",
        "image3": "pantalon_homme/pantalon3_marron.jpg",
        "image4": "pantalon_homme/pantalon4_marron.jpg",
        "index": "8"
    },
    {
        "type": "Homme Slim Fit Chino Trousers ",
        "prixmin": "9.95",
        "prixmax": "21.90",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Bleu",
        "description": ["98% Coton, 2% Élasthanne", "lavage en machine (40°C)", "Fermeture: Fermeture éclair", "taille normale"],
        "image1": "pantalon_homme/pantalon1_bleu.jpg",
        "image2": "pantalon_homme/pantalon2_bleu.jpg",
        "image3": "pantalon_homme/pantalon3_bleu.jpg",
        "image4": "pantalon_homme/pantalon4_bleu.jpg",
        "index": "9"
    },
    {
        "type": "Bermuda Chino Homme",
        "prixmin": "5.70",
        "prixmax": "19.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["98% Coton, 2% Élasthanne", "lavage en machine (40°C)", "Fermeture: Fermeture éclair", "taille normale"],
        "image1": "pantalon_homme/bermuda1_noir.jpg",
        "image2": "pantalon_homme/bermuda2_noir.jpg",
        "image3": "pantalon_homme/bermuda3_noir.jpg",
        "image4": "pantalon_homme/bermuda4_noir.jpg",
        "index": "10"
    },
    {
        "type": "Slim Formal - pantalon de Costume - Homme",
        "prixmin": "20.91",
        "prixmax": "40",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["68% Polyester, 32% Rayonne", "lavage en machine (30°C)", "Fermeture: Fermeture éclair", "taille normale"],
        "image1": "pantalon_homme/pantalon1_noir1.jpg",
        "image2": "pantalon_homme/pantalon2_noir1.jpg",
        "image3": "pantalon_homme/pantalon3_noir1.jpg",
        "image4": "pantalon_homme/pantalon4_noir1.jpg",
        "index": "11"
    },
//    CHEMISES
    {
        "type": "Chemise Slim Fit Repassage Facile à Manches Longues Respirant",
        "prixmin": "24.99",
        "prixmax": "29.99",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Bleue",
        "description": ["Composition matiere: 100% polyester", "Instructions entretien: Lavage à la mains et lavage à la machine", "Fermeture: Bouton",
            "taille normale", "Type de col: Type de col: Col chemise classique", "taille_ajustée", "Manches longues"],
        "image1": "chemise_homme/chemise_bleue.jpg",
        "image2": "chemise_homme/chemise_bleue.jpg",
        "image3": "chemise_homme/chemise_bleue.jpg",
        "image4": "chemise_homme/chemise_bleue.jpg",
        "index": "12"
    },
    {
        "type": "Chemise à Carreaux Manche Longue Coton Slim Fit Casual Mince",
        "prixmin": "16.99",
        "prixmax": "19.99",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Bleue",
        "description": ["Composition matiere: 100% coton",
            "Instructions entretien: Lavage à la mains et lavage à la machine",
            "Fermeture: Bouton", "Type de col: Col revers",
            "Type d'ajustement: taille normale", "Type manche: Manches longues"],
        "image1": "chemise_homme/chemise_carreaux1.jpg",
        "image2": "chemise_homme/chemise_carreaux2.jpg",
        "image3": "chemise_homme/chemise_carreaux3.jpg",
        "image4": "chemise_homme/chemise_carreaux4.jpg",
        "index": "13"
    },
    {
        "type": "Jack & Jones Jjegingham Shirt L/S Chemise Casual Homme",
        "prixmin": "24.99",
        "prixmax": "29.99",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Rouge",
        "description": ["100% Coton", "Lavable En Machine", "Fermeture: Bouton", "Type de col: Col Chemise Classique",
            "Manches longues"],
        "image1": "chemise_homme/chemise_rouge1.jpg",
        "image2": "chemise_homme/chemise_rouge2.jpg",
        "image3": "chemise_homme/chemise_rouge3.jpg",
        "image4": "chemise_homme/chemise_rouge4.jpg",
        "index": "14"
    },
    {
        "type": "chemise homme à manches longues / affaires loisirs mariage / repassage facile / Coupe ajustée",
        "prixmin": "12.89",
        "prixmax": "24.89",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Grise",
        "description": ["70% Coton, 30% Polyester", "Type de col: Col Chemise Classique",
            "taille_ajustée", "Manches longues"],
        "image1": "chemise_homme/chemise_grise1.jpg",
        "image2": "chemise_homme/chemise_grise2.jpg",
        "image3": "chemise_homme/chemise_grise3.jpg",
        "image4": "chemise_homme/chemise_grise4.jpg",
        "index": "15"
    },
    {
        "type": "Hommes décontractés Slim à Manches Longues ",
        "prixmin": "7.99",
        "prixmax": "11.39",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Balnche",
        "description": ["Coton et polyster", "Lavage à la main ou lavage en machine doux. Ne pas javelliser.",
            "Fermeture: Fermeture bouton", "Type de col: Col chemise classique",
            "Manches longues"],
        "image1": "chemise_homme/chemise_blanche1.jpg",
        "image2": "chemise_homme/chemise_blanche2.jpg",
        "image3": "chemise_homme/chemise_blanche3.jpg",
        "image4": "chemise_homme/chemise_blanche4.jpg",
        "index": "16"
    },
    {
        "type": "Wrangler Ls Western Shirt Chemise Casual Homme",
        "prixmin": "22.99",
        "prixmax": "74.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Rouge",
        "description": ["100% Coton", "L'avage en machine, 40° et +", "Type de col: Col À Boutons", "Manches longues"],
        "image1": "chemise_homme/chemise_western1.jpg",
        "image2": "chemise_homme/chemise_western2.jpg",
        "image3": "chemise_homme/chemise_western3.jpg",
        "image4": "chemise_homme/chemise_western4.jpg",
        "index": "17"
    },
    //Manteaux et Blousons Homme
    {
        "type": "Schott NYC Oakland Blouson Homme",
        "prixmin": "64.08",
        "prixmax": "130.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["100% Polyamide", "Lavage en machine, 30° max.", "Type de col: Col à fermeture éclair",
            "Manches longues"],
        "image1": "manteaux_blousons_homme/blouson1_noir.jpg",
        "image2": "manteaux_blousons_homme/blouson2_noir.jpg",
        "image3": "manteaux_blousons_homme/blouson3_noir.jpg",
        "image4": "manteaux_blousons_homme/blouson4_noir.jpg",
        "index": "18"
    },
    {
        "type": "Veste Hommes Blouson Léger Militaire Veste de Randonnée Imperméable Veste d'Extérieur Jogging Sport Manteau à Capuche",
        "prixmin": "29.99",
        "prixmax": "49.99",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Vert",
        "description": ["100% Polyester", "Lavage à la machine"],
        "image1": "manteaux_blousons_homme/blouson_militaire1.jpg",
        "image2": "manteaux_blousons_homme/blouson_militaire2.jpg",
        "image3": "manteaux_blousons_homme/blouson_militaire3.jpg",
        "image4": "manteaux_blousons_homme/blouson_militaire4.jpg",
        "index": "19"
    },
    {
        "type": "GRACEART Hommes Blousons Manteau Costume Longue Manches Jacket Coat Steampunk Gothique Costume",
        "prixmin": "49.99",
        "prixmax": "89.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir-Rouge",
        "description": ["100% Coton"],
        "image1": "manteaux_blousons_homme/blouson_noir_rouge1.jpg",
        "image2": "manteaux_blousons_homme/blouson_noir_rouge2.jpg",
        "image3": "manteaux_blousons_homme/blouson_noir_rouge3.jpg",
        "image4": "manteaux_blousons_homme/blouson_noir_rouge4.jpg",
        "index": "20"
    },
    {
        "type": "Levi's Type 3 Sherpa Trucker Veste en Jean Homme ",
        "prixmin": "61.26",
        "prixmax": "154.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Beige",
        "description": ["100% Coton", "Lavage en machine, 30° max.", "Fermeture: Bottone",
            "Type de col: Col Chemise Classique", "Manches longues"],
        "image1": "manteaux_blousons_homme/blouson_beige1.jpg",
        "image2": "manteaux_blousons_homme/blouson_beige2.jpg",
        "image3": "manteaux_blousons_homme/blouson_beige3.jpg",
        "image4": "manteaux_blousons_homme/blouson_beige4.jpg",
        "index": "21"
    },
    {
        "type": "Doudoune à Capuche Amovible, Coupe Droite - Meter - Homme",
        "prixmin": "45.52",
        "prixmax": "89.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Bleu",
        "description": ["100% Polyester", "Lavage en machine, 30° max.", "Type de col: Col à  fermeture éclair",
            "taille normale", "Manches longues"],
        "image1": "manteaux_blousons_homme/doudoune_bleue1.jpg",
        "image2": "manteaux_blousons_homme/doudoune_bleue2.jpg",
        "image3": "manteaux_blousons_homme/doudoune_bleue3.jpg",
        "image4": "manteaux_blousons_homme/doudoune_bleue4.jpg",
        "index": "22"
    },
    {
        "type": "Homme Hiver Chaud Polaires Doublé Sweats à Capuche Cotton Manteaux Doux Blousons Sweat-Shirts Outwear Tops",
        "prixmin": "13.99",
        "prixmax": "30.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["Mélange de coton", "Lavage en machine,séchage à l'égouttement à l'ombre, fer à repasser faible",
            "taille normale", "Manches longues"],
        "image1": "manteaux_blousons_homme/polaire_noir1.jpg",
        "image2": "manteaux_blousons_homme/polaire_noir2.jpg",
        "image3": "manteaux_blousons_homme/polaire_noir3.jpg",
        "image4": "manteaux_blousons_homme/polaire_noir4.jpg",
        "index": "23"
    },
    //Bonnets, casquettes chapeaux
    {
        "type": "Mammut Alnasca Cap Casquette Homme ",
        "prixmin": "32.50",
        "prixmax": "39.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Bleue",
        "description": ["Casquette filet avec logo Mammut brodé", "Intérieur en polaire", "Visière légèrement courbée", "Réglable à l'arrière"],
        "image1": "casquettes_bonnets_chapeaux_homme/casquette_bleue1.jpg",
        "image2": "casquettes_bonnets_chapeaux_homme/casquette_bleue2.jpg",
        "image3": "casquettes_bonnets_chapeaux_homme/casquette_bleue3.jpg",
        "image4": "casquettes_bonnets_chapeaux_homme/casquette_bleue4.jpg",
        "index": "24"
    },
    {
        "type": "Casquette_bleue",
        "prixmin": "34.19",
        "prixmax": "59.95",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["55% Laine, 45% Acrylique", "Non lavable"],
        "image1": "casquettes_bonnets_chapeaux_homme/casquette_souple1.jpg",
        "image2": "casquettes_bonnets_chapeaux_homme/casquette_souple2.jpg",
        "image3": "casquettes_bonnets_chapeaux_homme/casquette_souple3.jpg",
        "image4": "casquettes_bonnets_chapeaux_homme/casquette_souple4.jpg",
        "index": "25"
    },
    {
        "type": "CACUSS Bonnet Jersey tricoté Chapeau Unisexe Beanie Hip-Hop Printemps/été pour Hommes Femmes",
        "prixmin": "12.99",
        "prixmax": "17.08",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Gris",
        "description": ["100% Coton"],
        "image1": "casquettes_bonnets_chapeaux_homme/bonnet_gris1.jpg",
        "image2": "casquettes_bonnets_chapeaux_homme/bonnet_gris2.jpg",
        "image3": "casquettes_bonnets_chapeaux_homme/bonnet_gris3.jpg",
        "image4": "casquettes_bonnets_chapeaux_homme/bonnet_gris4.jpg",
        "index": "26"
    },
    {
        "type": "DonDon Bonnet pour l'hiver avec design classique et moderne ",
        "prixmin": "9.99",
        "prixmax": "12.99",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["100% Acrylique"],
        "image1": "casquettes_bonnets_chapeaux_homme/bonnet_noir1.jpg",
        "image2": "casquettes_bonnets_chapeaux_homme/bonnet_noir2.jpg",
        "image3": "casquettes_bonnets_chapeaux_homme/bonnet_noir3.jpg",
        "image4": "casquettes_bonnets_chapeaux_homme/bonnet_noir4.jpg",
        "index": "27"
    },
    {
        "type": "Classic Italy - Chapeau Trilby Homme ou Femme Classic Trilby Skye",
        "prixmin": "23.99",
        "prixmax": "32.00",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Noir",
        "description": ["Polyester"],
        "image1": "casquettes_bonnets_chapeaux_homme/chapeau_noir1.jpg",
        "image2": "casquettes_bonnets_chapeaux_homme/chapeau_noir2.jpg",
        "image3": "casquettes_bonnets_chapeaux_homme/chapeau_noir3.jpg",
        "image4": "casquettes_bonnets_chapeaux_homme/chapeau_noir4.jpg",
        "index": "28"
    },
    {
        "type": "Stetson Chapeau Traveller du Vagabond de Soleil ",
        "prixmin": "69.00",
        "prixmax": "81.59",
        "taille": ["x-small", "small", "medium", "large", "x-large"],
        "couleur": "Marron",
        "description": ["50% Coton, 50% Polyester"],
        "image1": "casquettes_bonnets_chapeaux_homme/stetson1.jpg",
        "image2": "casquettes_bonnets_chapeaux_homme/stetson2.jpg",
        "image3": "casquettes_bonnets_chapeaux_homme/stetson3.jpg",
        "image4": "casquettes_bonnets_chapeaux_homme/stetson4.jpg",
        "index": "29"
    },
    // Jupes          
    {
        "type": "Bridesmay Jupe Patineuse Courte Mini en Polyester Plissée",
        "prixmin": "13.99",
        "prixmax": "20.00",
        "taille": ["34", "36", "38", "40", "42"],
        "couleur": "Noire",
        "description": ["★Matière: en tissu extensible, très agréable à porter",
            "★Parfait pour la danse, le ballet, les costumes, les déguisements, le jazz et les faveurs du parti. Peut également être porté jupon, robe vintage et autre occasion. Vous pouvez aussi le porter seul comme une jupe",
            "★Au niveau de la taille, il est élastique",
            "★La jupe est divisée en modèles MINI et MIDI, veuillez choisir en fonction de vos besoins.",
            "★La jupe mi-cuisse va allonger vos jambes. Elle va bien avec un chemisier, un haut, ou un pull."],
        "image1": "jupes/minijupe_noire1.jpg",
        "image2": "jupes/minijupe_noire2.jpg",
        "image3": "jupes/minijupe_noire3.jpg",
        "image4": "jupes/minijupe_noire4.jpg",
        "index": "30"
    },
    {
        "type": "Hoerev Femmes Filles Courte Haute taille plissé Skieur Jupe école de Tennis",
        "prixmin": "16.57",
        "prixmax": "20.59",
        "taille": ["34", "36", "38", "40", "42"],
        "couleur": "Blanche",
        "description": ["Coton 30%"],
        "image1": "jupes/minijupe_blanche1.jpg",
        "image2": "jupes/minijupe_blanche2.jpg",
        "image3": "jupes/minijupe_blanche3.jpg",
        "image4": "jupes/minijupe_blanche4.jpg",
        "index": "31"
    },
    {
        "type": "Esprit Jupe Femme",
        "prixmin": "27.99",
        "prixmax": "51.10",
        "taille": ["34", "36", "38", "40", "42"],
        "couleur": "Grise",
        "description": ["76% Polyester, 22% Viscose, 2% Élasthanne", "Lavage en machine, 30° max."],
        "image1": "jupes/jupe_grise1.jpg",
        "image2": "jupes/jupe_grise2.jpg",
        "image3": "jupes/jupe_grise3.jpg",
        "image4": "jupes/jupe_grise4.jpg",
        "index": "32"
    },
    {
        "type": "Jupe Mi-Longue taille Haute Asymétrique Vintage Femme",
        "prixmin": "17.88",
        "prixmax": "20.00",
        "taille": ["34", "36", "38", "40", "42"],
        "couleur": "Beige",
        "description": ["100% Polyester"],
        "image1": "jupes/jupe_beige1.jpg",
        "image2": "jupes/jupe_beige2.jpg",
        "image3": "jupes/jupe_beige3.jpg",
        "image4": "jupes/jupe_beige4.jpg",
        "index": "33"
    },
    {
        "type": "Superdry Pleated Midi Skirt Jupe Femme ",
        "prixmin": "28.80",
        "prixmax": "59.99",
        "taille": ["34", "36", "38", "40", "42"],
        "couleur": "Noire",
        "description": ["100% Polyester", "Lavage en machine, 30° max."],
        "image1": "jupes/jupe_midi1.jpg",
        "image2": "jupes/jupe_midi2.jpg",
        "image3": "jupes/jupe_midi3.jpg",
        "image4": "jupes/jupe_midi4.jpg",
        "index": "34"
    },
    {
        "type": "Esprit Jupe Femme",
        "prixmin": "32.12",
        "prixmax": "39.99",
        "taille": ["34", "36", "38", "40", "42"],
        "couleur": "",
        "description": ["68% Polyester, 16% Viscose, 15% Coton, 1% Élasthanne", "Non lavable"],
        "image1": "jupes/jupe_esprit1.jpg",
        "image2": "jupes/jupe_esprit2.jpg",
        "image3": "jupes/jupe_esprit3.jpg",
        "image4": "jupes/jupe_esprit4.jpg",
        "index": "35"
    },
    //Escarpins
    {
        "type": "Escarpins à Plateforme Femme ",
        "prixmin": "18.65",
        "prixmax": "60",
        "taille": ["35", "36", "37", "38", "39"],
        "couleur": "Noir",
        "description": ["Dessus: Synthétique", "Doublure: Textile", "Semelle intérieure: Synthétique",
            "Matériau de semelle: Synthétique", "Type de talons: Plat", "Hauteur de talons: 8 centimètres",
            "Fermeture: A enfiler"],
        "image1": "escarpins/escarpin_noir1.jpg",
        "image2": "escarpins/escarpin_noir2.jpg",
        "image3": "escarpins/escarpin_noir3.jpg",
        "image4": "escarpins/escarpin_noir4.jpg",
        "index": "36"
    },
    {
        "type": "Escarpin argenté",
        "prixmin": "47.28",
        "prixmax": "90",
        "taille": ["35", "36", "37", "38", "39"],
        "couleur": "Argenté",
        "description": ["Dessus: Autres Cuir", "Doublure: Cuir", "Semelle intérieure: Cuir",
            "Matériau de semelle: Caoutchouc", "Type de talons: Cônique",
            "Hauteur de talons: 8.5 centimètres", "Largeur de la chaussure: Regular", "Fermeture: A enfiler"],
        "image1": "escarpins/escarpin_argente1.jpg",
        "image2": "escarpins/escarpin_argente2.jpg",
        "image3": "escarpins/escarpin_argente3.jpg",
        "image4": "escarpins/escarpin_argente4.jpg",
        "index": "37"
    },
    {
        "type": "Escarpins Bride Cheville Femme",
        "prixmin": "39.95",
        "prixmax": "49.95",
        "taille": ["35", "36", "37", "38", "39"],
        "couleur": "Noir",
        "description": ["Dessus: Toile", "Doublure: Textile", "Semelle intérieure: Synthétique",
            "Matériau de semelle: Synthétique", "Type de talons: Plat", "Fermeture: A enfiler"],
        "image1": "escarpins/escarpin_bride1.jpg",
        "image2": "escarpins/escarpin_bride2.jpg",
        "image3": "escarpins/escarpin_bride3.jpg",
        "image4": "escarpins/escarpin_bride4.jpg",
        "index": "38"
    },
    {
        "type": "Escarpins Bout fermé ",
        "prixmin": "16.50",
        "prixmax": "45.00",
        "taille": ["35", "36", "37", "38", "39"],
        "couleur": "Noir",
        "description": ["Dessus: Satin", "Doublure: Synthétique", "Semelle intérieure: Synthétique",
            "Matériau de semelle: Synthétique", "Type de talons: Aiguille", "Hauteur de talons: 7.5 centimètres",
            "Fermeture: A enfiler"],
        "image1": "escarpins/escarpin_ferme1.jpg",
        "image2": "escarpins/escarpin_ferme2.jpg",
        "image3": "escarpins/escarpin_ferme3.jpg",
        "image4": "escarpins/escarpin_ferme4.jpg",
        "index": "39"
    },
    {
        "type": "Buffalo Aphrodite, Escarpins Femme",
        "prixmin": "45.99",
        "prixmax": "71.33",
        "taille": ["35", "36", "37", "38", "39"],
        "couleur": "Multicolor",
        "description": ["Dessus: Cuir - Synthétique/PU", "Doublure: Synthétique", "Semelle intérieure: Cuir",
            "Matériau de semelle: Synthétique", "Type de talons: Aiguille", "Fermeture: A enfiler"],
        "image1": "escarpins/escarpin_buffalo1.jpg",
        "image2": "escarpins/escarpin_buffalo2.jpg",
        "image3": "escarpins/escarpin_buffalo3.jpg",
        "image4": "escarpins/escarpin_buffalo4.jpg",
        "index": "40"
    },
    {
        "type": "Dame Escarpins Classiques ",
        "prixmin": "37.73",
        "prixmax": "62.36",
        "taille": ["35", "36", "37", "38", "39"],
        "couleur": "Flower",
        "description": ["Dessus: Synthétique", "Doublure: Textile", "Matériau de semelle: Synthétique",
            "Type de talons: Plat", "Hauteur de talons: 8 centimètres", "Largeur de la chaussure: normal",
            "Fermeture: A enfiler"],
        "image1": "escarpins/escarpin_flower1.jpg",
        "image2": "escarpins/escarpin_flower2.jpg",
        "image3": "escarpins/escarpin_flower3.jpg",
        "image4": "escarpins/escarpin_flower4.jpg",
        "index": "41"
    },
    //Sacs
    {
        "type": "BIOZOYG greenMAXX Sac à Dos Sansa Pet I Sac à Dos en Feutre écologique pour Femmes et Hommes recyclé I Sac Stable de magasinage avec Poche intérieure I Pochette Tous Les Jours 35 x 43 x 12 cm Petrol",
        "prixmin": "43.70",
        "prixmax": "43.70",
        "taille": ["1"],
        "couleur": "Petrole",
        "description": ["QUALITÉ D'ALLEMAGNE - Le sac à dos en feutre de haute qualité pour hommes et femmes est facile à nettoyer, antitache et hydrofuge, avec une épaisseur de matériau 2 mm, le sac à dos est durable",
            "DURABLE ET ENVIRONNEMENTAL - Le sac à dos élégant est fabriqué à partir de bouteilles en PET recyclées comme une alternative au polyester classique avec un aspect de cuir lisse robuste",
            "SAC À DOS EN FEUTRE PRATIQUE - Le sac à dos Shopping a une poche intérieure pratique et un rabat d’enveloppe à double fermeture avec code. Bandoulière en sangle de haute qualité",
            "SAC À DOS 2 en 1 - Avec Sansa PET, vous avez à la fois votre sac à dos et votre sac à main: tirez les sangles vers le haut à l'arrière de la poignée pour obtenir un sac à main",
            "greenMAXX est synonyme de durabilité et d'alternance respectueuses de l'environnement anti le plastique nocif - notre gamme se compose donc de matières premières renouvelables et recyclées"],
        "image1": "sacs/sac_petrole1.jpg",
        "image2": "sacs/sac_petrole2.jpg",
        "image3": "sacs/sac_petrole3.jpg",
        "image4": "sacs/sac_petrole4.jpg",
        "index": "42"
    },
    {
        "type": "Sac Ordinateur Portable 15.6 Pouces Femmes, Sac Fourre-tout Sac Cabas Sac Epaule Sac à Main en PU Cuir Grand Capacité Sac Bandoulière Sac à épaule, Imperméable Sac de Cours Bandoulière, Avec Bandouliè ",
        "prixmin": "46.99",
        "prixmax": "46.99",
        "taille": ["1"],
        "couleur": "Gris",
        "description": ["SUPER GRANDE CAPACITÉ: Ce sac pour ordinateur portable a une très grande capacité (40x14x32.5cm). Vous pouvez même y installer un ordinateur portable de 15,6 pouces, très pratique pour le travail, les études, etc.",
            "DE NOMBREUX PLATEAUX POUR UN MEILLEUR STOCKAGE: Ce sac contient de nombreux compartiments (un à fermeture à glissière) et de nombreux sachets pour que vous puissiez y ranger beaucoup de choses.",
            "AVEC POIGNÉE AJUSTABLE: La poignée du sac à main est réglable, elle peut être ajustée de 53 cm à 76 cm, et les poignées sont également très confortables.",
            "MATÉRIAU DE HAUTE QUALITÉ: L’extérieur de cette élégante mallette est en cuir PU de haute qualité, imperméable et doux; le matériau intérieur est un tissu en polyester, sec et anti-poussière.",
            "12 MOIS RÉSOUDRE LES PROBLÈMES: Si vous rencontrez un problème avec nos produits, contactez-nous par Amazon, nous vous répondrons dans les 24 heures."],
        "image1": "sacs/sac_laptop1.jpg",
        "image2": "sacs/sac_laptop2.jpg",
        "image3": "sacs/sac_laptop3.jpg",
        "image4": "sacs/sac_laptop4.jpg",
        "index": "43"
    },
    {
        "type": "Sac à Main Femme Géométriques Mode Chic, Unique Sac Bandoulière Capacité Moyenne, Portefeuille ",
        "prixmin": "23.99",
        "prixmax": "23.99",
        "taille": ["1"],
        "couleur": " S- Crossbody",
        "description": ["Géométriques Mode Chic"],
        "image1": "sacs/sac_lovelook1.jpg",
        "image2": "sacs/sac_lovelook2.jpg",
        "image3": "sacs/sac_lovelook3.jpg",
        "image4": "sacs/sac_lovelook4.jpg",
        "index": "44"
    },
    {
        "type": "Desigual 19WAXP85, sac à main femme 24x9x29.5 cm (B x H x T) ",
        "prixmin": "66.62",
        "prixmax": "66.62",
        "taille": ["1"],
        "couleur": "Marron",
        "description": ["Équipement : compartiment à fermeture Éclair, poche(s) extérieure(s)",
            "poignée", "Type de fermeture : fermeture Éclair", "Volume en L. env.: 11-20",
            "Série : Bols Tekila Sunrise Loverty"],
        "image1": "sacs/sac_desigual1.jpg",
        "image2": "sacs/sac_desigual2.jpg",
        "image3": "sacs/sac_desigual3.jpg",
        "image4": "sacs/sac_desigual4.jpg",
        "index": "45"
    },
    {
        "type": "Miss Lulu Sac à Main Femme 2pcs avec Pochette Bandoulière en Cuir PU",
        "prixmin": "23.99",
        "prixmax": "23.99",
        "taille": ["1"],
        "couleur": "Gris",
        "description": ["Grand sac à main fourre-tout de forme et de taille parfaite avec un sac de rangement, peut être utilisé comme sac à bandoulière avec une longue bandoulière réglable et amovible.",
            "Dimensions : Longueur 33cm, Largeur 13cm, Hauteur 23cm, Poignée 18cm. Sac à main léger pouvant contenir tous vos objets quotidiens : livres, lunettes, portefeuille, téléphone, tablette, clés, produit de beauté, parfum, etc.",
            "Matière : Fabriqué en Simili Cuir de haute qualité , texture douce et brillante, résistant à la déchirure. Les crochets / anneaux en D / tirants / goujons en métaux solides et en métaux durs sont tous en alliage de zinc de couleur dorée pâle.",
            "Structure : un compartiment principal avec fermeture à glissière, 2 poches intérieures à fonctions, 1 petite poche à fermeture éclair. 1 poche zippée à l'arrière. C'est un bon choix pour un anniversaire ou un cadeau de Noël.",
            "Caractéristiques : Les doubles poignées sont douces et procurent une sensation agréable. Multi-usages du sac pour le travail de bureau, l'école, les voyages, les voyages de courte durée, les achats."],
        "image1": "sacs/sac_lulu1.jpg",
        "image2": "sacs/sac_lulu2.jpg",
        "image3": "sacs/sac_lulu3.jpg",
        "image4": "sacs/sac_lulu4.jpg",
        "index": "46"
    },
    {
        "type": "Sac à Dos de Mode, JOSEKO Sac à Dos en Cuir PU véritable avec Rivet Sac à bandoulière en Cuir PU pour Sac à Dos pour Femme Noir",
        "prixmin": "39.99",
        "prixmax": "39.99",
        "taille": ["1"],
        "couleur": "Noir",
        "description": ["★ MATÉRIEL: matériel mis à jour pour la qualité du cuir PU. C'est un beau et simpliste design cuir fermeture à glissière fermeture mode femme sac à dos, quincaillerie silvermetal agréable au toucher, doublure de polyester durable.",
            "★ SIZE (LxHxW): 27cm * 13cm * 27cm * 10inin * 10.6in. Poids: 1.1kg / 2.4bs.",
            "★ design à la mode: vous pouvez le porter comme sac à bandoulière et sac à dos. Le cuir souple, la texture tendance, au style simple. Peu importe que vous soyez étudiant universitaire ou membre du bureau Madame, c’est un bon choix que de révéler votre noble tempérament. Ne sors jamais du style.",
            "★ Structures: la poche centrale a de grandes capacités pour ranger vos affaires. et il y a une poche à fermeture à glissière et une fente pour contenir votre carte, portefeuille, téléphone, etc. En outre, il y a une poche arrière avec fermeture à glissière sécurisée.",
            "★ couleur populaire: Le noir classique. Rendez-le facile à assortir les tenues. Si élégant que vous puissiez aller faire du shopping ou faire des activités en plein air."],
        "image1": "sacs/sac_a_dos1.jpg",
        "image2": "sacs/sac_a_dos2.jpg",
        "image3": "sacs/sac_a_dos3.jpg",
        "image4": "sacs/sac_a_dos4.jpg",
        "index": "47"
    },
    //Lunettes
    {
        "type": "MuJaJa Oversized lunettes de soleil femme UV400 Polarisées Lunettes de soleil-Protection 100% UVA/UVB",
        "prixmin": "19.69",
        "prixmax": "19.69",
        "taille": ["1"],
        "couleur": "Noir",
        "description": ["polarisé", "Largeur du verre: 2.16 pouces", "100% UVA/UVB Protection",
            "【Les lunettes de soleil UV400 】peuventbloquer 100% des rayons UVA et UVB, réduisent les reflets sur les routes, les étendues d'eau, la neige et les autres surfaces horizontales. Restaurer la vraie couleur, éliminer la lumière réfléchie et la lumière diffusée et protéger les yeux parfaitement",
            "【Qualité élevée】Les lunettes de soleil sont faites de matériaux de haute qualité PC qui sont assez durables pour une utilisation de longue durée. Ils conviennent à toutes les conditions climatiques et météorologiques"],
        "image1": "lunettes/lunette_mujaja1.jpg",
        "image2": "lunettes/lunette_mujaja2.jpg",
        "image3": "lunettes/lunette_mujaja3.jpg",
        "image4": "lunettes/lunette_mujaja4.jpg",
        "index": "48"
    },
    {
        "type": "FIMILU Lunettes de Soleil pour Femme Lunettes de Soleil Polarisées Classiques 100% UV400 Protection",
        "prixmin": "38.00",
        "prixmax": "38.00",
        "taille": ["1"],
        "couleur": "Rouge",
        "description": ["polarisé", "Largeur du verre: 5.9 centimètres", "100% UVA&UVB Protection",
            "【UV400 Protéger Vos Yeux】Ces lunettes de soleil sont de grandes lentilles TAC, qui bloquent 100% de la lumière ultraviolette et absorbent la majeure partie de la lumière noctive. Cela protégera vos yeux des rayons untraviolets du soleil qui peut vous blesser les yeux et même causer une cécité permanante. Vous n’avez pas à vous inquitéter pour l’extérieur et le soleil tant que vous êtes équipé de ces lunettes qui réduisent le rayonnement ultraviolet pour protéger vos yeux",
            "【Lentilles Polarisées HD】Les lentilles polarisées continnenent une fiction de filtre special,qui peut filtrer la lumière réfléchie forte et réduire l’ éblouissement et render la scène plus claire et plus douce. Les lunettes polariés ont de nombreux avantages dans la plupart des sports et des activités. Les lentilles polarisées combinées à d’autres fonctions peuvent améliorer l’expérience extérieure",
            "【Design Rétro de Grande Monture】La combination ingénieurse de monture surdimensionnée et de design d’ éléments classiques est la tendance de la journée! Design simple et exquis est la demande de mode d’aujourd’hui. Vous pouvez également les porter pour protéger vos yeux dans les activités quotidiennes telles que la conduite, le shopping et d’autre activités en plein air"],
        "image1": "lunettes/lunette_fimilu1.jpg",
        "image2": "lunettes/lunette_fimilu2.jpg",
        "image3": "lunettes/lunette_fimilu3.jpg",
        "image4": "lunettes/lunette_fimilu4.jpg",
        "index": "49"
    },
    {
        "type": "SOJOS Lunettes de Soleil Ronde pour Femme Fashion Nouveau Modèle BLOSSOM ",
        "prixmin": "17.89",
        "prixmax": "17.89",
        "taille": ["1"],
        "couleur": "Noir",
        "description": ["non-polarisé",
            "PROTECTION UV400 POUR VOS YEUX - Les lunettes de soleil antireflet SojoS avec lentilles polarisées HD peuvent filtrer les reflets du soleil et protéger vos yeux des dommages à long terme en bloquant à 100% les rayons nocifs UVA et UVB.",
            "UNIQUE STYLE - Ces lunettes de soleil rondes polarisées SojoS constituent un nouveau design à double pont rond en métal. Fabriqué en matériau métallique de haute qualité et charnières métalliques renforcées. Ce style élégant offre aux individus contemporains un look passe-partout avec un attrait contemporain irrésistible.",
            "LES EMBALLAGES CADEAU - Lunettes de soleil*1 , Sachet en microfibre souple*1, Tissu de verres souple*1 , Emballage exquis*1 .C'est aussi un cadeau bien emballé, une idée de cadeau merveilleuse et pratique pour les amis et la famille."],
        "image1": "lunettes/lunette_sojos1.jpg",
        "image2": "lunettes/lunette_sojos2.jpg",
        "image3": "lunettes/lunette_sojos3.jpg",
        "image4": "lunettes/lunette_sojos4.jpg",
        "index": "50"
    },
    {
        "type": "Polaroid - Lunette de soleil P8317 Rectangulaire - Femme Noir one size",
        "prixmin": "35.77",
        "prixmax": "35.77",
        "taille": ["1"],
        "couleur": "Noir",
        "description": ["Non polarisée", "Largeur du verre: 5.8 centimètres", "Hauteur du verre: 1 millimètres",
            "Pont: 15 millimètres", "3", "Protective case included"],
        "image1": "lunettes/lunette_polaroid1.jpg",
        "image2": "lunettes/lunette_polaroid2.jpg",
        "image3": "lunettes/lunette_polaroid3.jpg",
        "image4": "lunettes/lunette_polaroid4.jpg",
        "index": "51"
    },
    {
        "type": "Kennifer Lunettes de soleil rondes style cercle steampunk inspiré rondes pour femmes",
        "prixmin": "20.09",
        "prixmax": "20.09",
        "taille": ["1"],
        "couleur": "Rose",
        "description": ["polarisé", "Largeur du verre: 50 millimètres",
            "CLASSIC RETRO DESIGN - La collection de lunettes de soleil de style rond classique répond toujours aux exigences de la mode actuelle. Convient pour les hommes et les femmes. Convient à n'importe quel visage.",
            "LENTILLE POLARISÉE HD - Les lentilles Kennifer Polarized sont fabriquées dans des matériaux de haute qualité. Elles offrent une protection à 100% contre les rayons UVA, UVB et UVC, tout en réduisant les reflets lorsque vous conduisez ou que vous vous déplacez. vous portez des lunettes de soleil polarisées Kennifer au soleil.",
            "OCCASION - Les lunettes de soleil Kennifer sont les meilleures amies pour le soleil, en particulier pour la conduite, les voyages, la pêche, l’équitation, la prise de photos, etc."],
        "image1": "lunettes/lunette_kenifer1.jpg",
        "image2": "lunettes/lunette_kenifer2.jpg",
        "image3": "lunettes/lunette_kenifer3.jpg",
        "image4": "lunettes/lunette_kenifer4.jpg",
        "index": "52"
    },
    {
        "type": "Guess Sunglasses Gu7597 83B 56 Montures de Lunettes, Violet (Violett), Femme",
        "prixmin": "44.90",
        "prixmax": "44.90",
        "taille": ["1"],
        "couleur": "Violette",
        "description": ["Non polarisée", "Hauteur du verre: 5.1 centimètres", "Pont: 18 millimètres",
            "100% UVA & UVB", "Guess Lunettes de soleil Femme/Violet", "Lunettes 100% UVA et UVB"],
        "image1": "lunettes/lunette_guess1.jpg",
        "image2": "lunettes/lunette_guess2.jpg",
        "image3": "lunettes/lunette_guess3.jpg",
        "image4": "lunettes/lunette_guess4.jpg",
        "index": "53"
    },
    //Baskets
    {
        "type": "KOUDYEN Chaussures de Sport Course Homme Femme Basket Lacets Fitness Confortable Sneakers Trail Running Shoes",
        "prixmin": "26.99",
        "prixmax": "32.99",
        "taille": ["37", "39", "41", "43", "45"],
        "couleur": "Grise",
        "description": ["Dessus: Synthétique.Empeigne en mesh tissé léger, respirant et doux, pour ne pas vous sentir étouffant pendant longtemps.",
            "Doublure: Textile.La doublure à l'épreuve de l'humidité garde vos pieds au sec, des semelles intérieures rembourrées et une doublure respirante pour un soutien supérieur et un confort accru.",
            "Matériau de semelle: Gomme / Synthétique.Antidérapante et résistante à l'usure, améliore la flexibilité et la stabilité, permet à vos pieds d'avoir un meilleur degré de liberté.",
            "Type de talons: Plat",
            "Hauteur de talons: 2 centimètres",
            "Tour de mollet: normale",
            "Largeur de la chaussure: Normal.Acheter à taille normale"],
        "image1": "baskets/baskets_koudyen1.jpg",
        "image2": "baskets/baskets_koudyen2.jpg",
        "image3": "baskets/baskets_koudyen3.jpg",
        "image4": "baskets/baskets_koudyen4.jpg",
        "index": "54"
    },
    {
        "type": "Air Running Baskets Chaussures Homme Femme Outdoor Gym Fitness Sport Sneakers Style Multicolore Respirante",
        "prixmin": "33.88",
        "prixmax": "53.88",
        "taille": ["37", "39", "41", "43", "45"],
        "couleur": "bleurose",
        "description": ["Dessus: Synthétique. Respirant, absorbant la transpiration, léger pour plus de confort et d'agilité.",
            "Doublure: Textile. Intérieur respirant et confortable avec des semelles souples.",
            "Matériau de semelle: Caoutchouc. Semelle intérieure en caoutchouc, coussin d'air résistant, absorption maximale des chocs.",
            "Type de talons: Plat. Flexibilité et douceur. Les chaussures flexibles peuvent être pliées librement, sans aucune pression lorsque vous les portez pour courir ou faire quoi que ce soit.",
            "Hauteur de talons: 3 centimètres",
            "Largeur de la chaussure: normale",
            "Fermeture: Lacets. La mode des Baskets et ses nombreuses fonctionnalités peuvent être utilisées pour la course, le fitness, la randonnée, le tourisme, les sports de plein air, etc."],
        "image1": "baskets/baskets_air1.jpg",
        "image2": "baskets/baskets_air2.jpg",
        "image3": "baskets/baskets_air3.jpg",
        "image4": "baskets/baskets_air4.jpg",
        "index": "55"
    },
    {
        "type": "Axcone Homme Femme Air Baskets Chaussures Outdoor Running Gym Fitness Sport Sneakers Style Running",
        "prixmin": "33.95",
        "prixmax": "53.95",
        "taille": ["37", "39", "41", "43", "45"],
        "couleur": "Noire",
        "description": ["Dessus: Synthétique,Respirant, absorbant la transpiration, léger pour plus de confort et d'agilité.",
            "Doublure: textile,Intérieur respirant et confortable avec des semelles souples.",
            "Matériau de semelle: Caoutchouc,Semelle intérieure en caoutchouc, coussin d'air résistant, absorption maximale des chocs.",
            "Type de talons: Plat,La mode des Baskets et ses nombreuses fonctionnalités peuvent être utilisées pour la course, le fitness, la randonnée, le tourisme, les sports de plein air, etc.",
            "Hauteur de talons: 3 centimètres",
            "Fermeture: Lacets"],
        "image1": "baskets/baskets_axcone1.jpg",
        "image2": "baskets/baskets_axcone2.jpg",
        "image3": "baskets/baskets_axcone3.jpg",
        "image4": "baskets/baskets_axcone4.jpg",
        "index": "56"
    },
    {
        "type": "Puma - Suede Classic+ - Baskets mode - Mixte Adulte ",
        "prixmin": "34.85",
        "prixmax": "59.85",
        "taille": ["37", "39", "41", "43", "45"],
        "couleur": "Noire",
        "description": ["Dessus: Autres Cuir", "Doublure: Textile", "Semelle intérieure: Synthétique",
            "Matériau de semelle: Caoutchouc", "Type de talons: Plat", "Hauteur de talons: 2 centimètres",
            "Largeur de la chaussure: Normal", "Fermeture: Lacets"],
        "image1": "baskets/baskets_puma1.jpg",
        "image2": "baskets/baskets_puma2.jpg",
        "image3": "baskets/baskets_puma3.jpg",
        "image4": "baskets/baskets_puma4.jpg",
        "index": "57"
    },
    {
        "type": "Adidas Gazelle Baskets Basses, Mixte Adulte, gris ",
        "prixmin": "51.71",
        "prixmax": "78.95",
        "taille": ["37", "39", "41", "43", "45"],
        "couleur": "Bleue",
        "description": ["Dessus: Synthétique", "Doublure: Textile", "Semelle intérieure: Fourrure Synthétique",
            "Matériau de semelle: Caoutchouc", "Type de talons: Plat", "Hauteur de talons: 2 centimètres",
            "Largeur de la chaussure: Normal"],
        "image1": "baskets/baskets_adidas1.jpg",
        "image2": "baskets/baskets_adidas2.jpg",
        "image3": "baskets/baskets_adidas3.jpg",
        "image4": "baskets/baskets_adidas4.jpg",
        "index": "58"
    },
    {
        "type": "TQGOLD Chaussure de Sport Homme Femme Basket de Running Fitness Course Sneakers Basses ",
        "prixmin": "26.99",
        "prixmax": "32.99",
        "taille": ["37", "39", "41", "43", "45"],
        "couleur": "Noire",
        "description": ["Dessus: Synthétique. ★taille:taille européenne standard.",
            "Doublure: Textile", "Matériau de semelle: Gomme / Synthétique", "Type de talons: Plat",
            "Hauteur de talons: 3 centimètres", "Largeur de la chaussure: Normal", "Fermeture: Lacets"],
        "image1": "baskets/baskets_tqgold1.jpg",
        "image2": "baskets/baskets_tqgold2.jpg",
        "image3": "baskets/baskets_tqgold3.jpg",
        "image4": "baskets/baskets_tqgold4.jpg",
        "index": "59"
    }
];